### PR TITLE
Fixes assignment of initialUrl in build store. Now initialUrl is assigned to urlFromQuery

### PR DESCRIPTION
**Pull request by orballo**
fixes https://github.com/frontity/saturn-theme/issues/21

### CODE REVIEW

**Comment by luisherranz** [comment]
Ok, so I guess `self.fetchHeadContent()` wasn't being called, and once you fixed that, the `build.initialUrl` wasn't properly populated. Is that right @orballo?

**Comment by orballo** [comment]
@luisherranz that's right

**Review by luisherranz — APPROVED** [review]
Ok, Thanks. Approved!

**Pull request merged**
