### PR TITLE
Fixes initialSelectedItem missing in client

### PR DESCRIPTION
**Pull request by orballo**
fixes https://github.com/frontity/frontity/issues/134

### CODE REVIEW

**Review by luisherranz — APPROVED** [review]
👍 

May I ask you why you need it in the client?

**Comment by luisherranz** [comment]
No problem, I saw it here https://github.com/frontity/frontity/issues/134 :)

**Comment by orballo** [comment]
Exactly, @luisherranz. Because of this view:

https://github.com/frontity/wp-org-connection/blob/0913fd4f43038a2c808246a4777537b0d2618746/src/pwa/stores/connection/head-meta.js#L22-L29

**Pull request merged**
